# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gHM_Epj7zE3GUkyNyy6NCQmNEXUdk-NG
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

dataset = pd.read_csv('/content/hiring.csv')
fill=[0,0,5,2,7,3,10,11]
for i in range(0,8):
  dataset['experience'][i]=fill[i]
dataset=dataset.fillna(0)
dataset

x =dataset.iloc[:, :3]
y =dataset.iloc[:, -1]

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()

regressor.fit(x,y)

pickle.dump(regressor, open('model.pkl','wb'))